### ISSUE TITLE
Protected function error

### ISSUE THREAD

**Issue by Kinetyk89** [EthanCentaurai/Chinchilla#16] opened 2018-07-30 11:22 UTC
1x [ADDON_ACTION_BLOCKED] AddOn 'Chinchilla' tried to call the protected function 'MainMenuBar:SetPoint()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetPoint'
FrameXML\UIParent.lua:2943: in function `UIParentManageFramePositions'
FrameXML\UIParent.lua:2326: in function <FrameXML\UIParent.lua:2313>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:3115: in function <FrameXML\UIParent.lua:3113>
[C]: in function `UIParent_ManageFramePositions'
FrameXML\BuffFrame.lua:331: in function `BuffFrame_UpdateAllBuffAnchors'
FrameXML\BuffFrame.lua:104: in function <FrameXML\BuffFrame.lua:87>
[C]: in function `BuffFrame_Update'
FrameXML\BuffFrame.lua:49: in function <FrameXML\BuffFrame.lua:45>

Locals:
InCombatSkipped

**Comment by EthanCentaurai** [comment] 2018-07-31 17:25
Duplicate of #11.

**Closed by EthanCentaurai** 2018-07-31 17:25 UTC
